pgoeiras/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from pgoapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.table_view),
    path('api/submit/', views.submit_form),
    path('faq/', views.faq, name="faq")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pgoapp/models.py
from django.db import models


class Player(models.Model):
    TEAM_CHOICES = (
        ('b', ''),
        ('i', 'Instinct'),
        ('m', 'Mystic'),
        ('v', 'Valor')
    )

    nickname = models.CharField(max_length=128)
    code = models.CharField(max_length=12)
    team = models.CharField(max_length=2, choices=TEAM_CHOICES, default='b')
    level = models.PositiveSmallIntegerField(default=0)
    active = models.BooleanField(default=True)
    creation = models.DateTimeField(auto_now_add=True)
    last_edit = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nickname

    @classmethod
    def create_or_activate(cls, form):
        try:
            player = cls.objects.get(nickname=form.cleaned_data['nickname'])
        except cls.DoesNotExist:
            player = form.save(commit=False)

        player.level = form.cleaned_data['level']
        player.team = form.cleaned_data['team']
        player.code = form.cleaned_data['code']
        player.active = True
        return player

    @classmethod
    def activate(cls, nickname):
        p = cls.objects.get(nickname=nickname)
        p.active = True
        p.save()

    @classmethod
    def deactivate(cls, nickname):
        p = cls.objects.get(nickname=nickname)
        p.active = False
        p.save()

pgoapp/forms.py
from django import forms

from pgoapp.models import Player


class PlayerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PlayerForm, self).__init__(*args, **kwargs)
        for _, f in self.fields.items():
            f.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Player
        fields = ['nickname', 'code', 'team', 'level']

pgoapp/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from pgoapp.forms import PlayerForm
from pgoapp.models import Player


def table_view(request):
    context = {
        'players': Player.objects.filter(active=True).order_by('creation'),
        'form': PlayerForm()
    }
    return render(request, "table.html", context=context)


@csrf_exempt
def submit(request):
    # TODO: refactor to use django forms
    if request.is_ajax():
        action = request.POST.get('action', 'create')

        nickname = request.POST['nickname']
        code = request.POST.get('code', None)
        level = request.POST.get('level', None)

        if action == 'create':
            player, created = Player.objects.get_or_create(nickname=nickname, defaults={'code': code, 'level': level})
            if not created:
                player.active = True
        else:
            player = Player.objects.get(nickname=nickname)
            if action == 'delete':
                player.active = False
            elif action == 'edit':
                player.active = True
                player.code = code
                player.level = level
            else:
                player.active = True
        player.save()
        data = {'status': 'ok'}
        return JsonResponse(data)


@csrf_exempt
def submit_form(request):
    action = request.POST.get('action', 'create')
    nickname = request.POST['nickname']
    if action == 'create' or action == 'edit':
        form = PlayerForm(request.POST)
        if form.is_valid():
            player = Player.create_or_activate(form)
            player.save()
    elif action == 'delete':
        Player.deactivate(nickname)
    else:
        Player.activate(nickname)

    return JsonResponse({'status': 'ok'})


# TODO: make this static
def faq(request):
    return render(request, "faq.html")

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% block extra_css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% block body %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block extra_js_bottom %}{% endblock %}
  </body>
</html>

templates/faq.html
{% extends 'base.html' %}
{% block title%}PG-Oeiras - FAQ{% endblock %}
{% block body %}
    <div class="container-fluid">
        <h3>O que é isto?</h3>
        <p>
            Projecto que contém a lista de jogadores de Pokemon GO na zona de Oeiras e os respectivos Códigos de Amigo.
            Qualquer pessoa pode enserir, editar ou apagar entradas da tabela.
        </p>
        <h3>Como é que isto está protegido contra alguém apagar a minha entrada?</h3>
        <p>
            Não é. Podia implementar uns controlos de acesso, mas isso implicava logins e mais passos para se conseguir
            uma coisa que era suposto ser mais simples do que manter a lista na conversa do whatsapp.
            Estou a assumir que a Internet está cheia de pessoas bem intencionadas :D
        </p>
        <h3>Encontrei um erro</h3>
        <p>
            Procura-me numa das conversas de grupo do whatsapp ou mail para <a href="mailto:alexbk00@gmail.com">alexbk00@gmail.com</a>.
            Não vou deixar aqui o meu número directamente porque estou a assumir que a internet está cheia de pessoas mal
            intencionadas...
        </p>
        <h3>Fixe fixe era se isto desse para fazer X</h3>
        <p>
            O mesmo que se faz para reportar erro OU ... <a href="https://gitlab.com/AlexIgnatiev/pgoeiras">https://gitlab.com/AlexIgnatiev/pgoeiras</a>.
            O código está aberto, podem colaborar
        </p>
    </div>
{% endblock %}

templates/table.html
{% extends 'base.html' %}

{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/add_player.css' %}">
{% endblock %}
{% block title %}Player Code List{% endblock %}

{% block body %}
    <div class="container">
        <form class="form-inline">
            {{ form }}
            <button type="submit" id="submit_new_player" class="btn btn-primary mb-2">Submit</button>
            <div id="ok-div" class="alert alert-success" style="display: none">OK</div>
            <div id="error-div" class="alert alert-danger" style="display: none">Error</div>
        </form>
        <a href="{% url "faq" %}">FAQ</a>
        <table id="main-tbl" class="table">
            <thead>
                <tr>
                    <th scope="col">nickname</th>
                    <th scope="col">code</th>
                    <th scope="col">copy</th>
                    <th scope="col">team</th>
                    <th scope="col">level</th>
                </tr>
            </thead>
            <tbody>
            {% for p in players %}
                <tr>
                    <td>{{ p.nickname }}</td>
                    <td>{{ p.code }}</td>
                    <td>
                        <button type="button" class="btn btn-default btn-sm btn-cpy">
                            <span class="glyphicon glyphicon-copy"></span> Copy
                        </button>
                    </td>
                    <td class="team-{{ p.team }}">{{ p.get_team_display }}</td>
                    <td>{{ p.level }}</td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
{% endblock %}

{% block extra_js_bottom %}
    <script src="{% static 'js/jquery.tabledit.min.js' %}"></script>
    <script>
        $(".btn-cpy").click(function(e) {
            const value = $(this)[0].parentElement.parentElement.children[1].innerText;
            const $temp = $("<input>");
            $("body").append($temp);
            $temp.val(value).select();
            document.execCommand("copy");
            $temp.remove();

        });

        function ok(_nickname, _code, _team, _level) {
            $('#main-tbl tr:last').after(
                '<tr>' +
                    '<td>' + _nickname + '</td>' +
                    '<td>' + _code + '</td>' +
                    '<td></td>' +
                    '<td>' + _team + '</td>' +
                    '<td>' + _level + '</td>' +
                '</tr>'
            );
            $('#ok-div').css('display', 'inline');
        }

        function error_fn() {
            $('#error-div').css('display', 'inline');
        }

        $('#main-tbl').Tabledit({
            url: '/api/submit/',
            columns: {
                identifier: [0, 'nickname'],
                editable: [
                    [1, 'code'],
                    [3, 'team', '{"b": "", "i": "Instinct", "m": "Mystic", "v": "Valor"}'],
                    [4, 'level']
                ]
            }
        });


        $("#submit_new_player").click(function(e) {
            e.preventDefault();
            const nickname = $("#id_nickname").val().replace(/\s/gi,"");
            const code = $("#id_code").val().replace(/\s/gi,"");
            const level = $("#id_level").val().replace(/\s/gi,"");
            const team = $("#id_team").val().replace(/\s/gi,"");
            $.ajax({
                url: "/api/submit/",
                type: "POST",
                data: {
                    "nickname": nickname,
                    "code": code,
                    "team": team,
                    "level": level
                },
                dataType: "json",
                success: function() {ok(nickname, code, team, level);},
                error: error_fn
            });
        });
    </script>
{% endblock %}